
# Site settings
title: "Arash Shams | Personal blog"
url: "https://blog.arashshams.com"
logo: ""

author: Arash Shams
fullname: "آرش شمس"
email: me@arashshams.com
author_twitter: ara4sh
author_avatar: ''

keywords: "cloud,virtualization,kvm,docker,qemu,xen,lxc,opennebula,cloudstack,archlinux,mysql,redis,mongodb,linux,glusterfs,apache,nginx,haproxy,loadbalancer,highavailability,سیس ادمین, لینوکس"
description: >
  سایت شخصی سید ناصر حسنی - نوشته های درباره‌ی برنامه‌نویسی، هنر و اجتماع.
long_description: >
  آرش شمس هستم مدیر سرور و بانک های اطلاعاتی در حال حاضر به صورت جدی روی scaling و database فعالبت میکنم. 


copyright: "Commons Attribution 4.0 International"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      author: "آرش شمس"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      author: "آرش شمس"


# Where things are
source:          ./src
destination:  ./public
#favicon: "img/favicon.png"


# Handling Reading
encoding:       "utf-8"
include:          [".htaccess", "CNAME", "README.md"]
keep_files:     [".git", "assets"]
exclude:         ["assets", "node_modules", "gulpfile.js", "package.json", "bower.json", "webpack.config.js"]


# Conversion
markdown: kramdown


# Serving
port:    8080


# Outputting
# baseurl: /xyz
permalink: /blog/:year/:title/
paginate_path: /blog/page:num
paginate: 5
timezone: Asia/Tehran


# Plugins
gems:
  - jalalidate
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

