
# Site settings
title: "naser.xyz | Seyed Naser Hasani"
url: "https://naser.xyz"
logo: "/assets/images/fav/android-touch-icon.png"

author: Seyed Naser Hasani
fullname: "سید ناصر حسنی"
email: snhasani@gmail.com
author_twitter: snhasani
author_avatar: '/assets/images/snh_winter-avatar_grayscale.jpg'

keywords: "کامپیوتر، بوتسترپ, بوتستراپ, فریمورک، لینوکس, برنامه‌نویسی، جاوااسکریپت، علم, اینترنت, آموزش, طاحی, css, html, scss, sass, javascript, nodejs, frontend, front-end, application, mobile, native, vanilla, cordova, bootstrap, phongap, android, npm, git, app, ios, linux, opensource, framework, dev-tools"
description: >
  سایت شخصی سید ناصر حسنی - نوشته های درباره‌ی برنامه‌نویسی، هنر و اجتماع.
long_description: >
  می‌نویسم؛ بیشترش درباره‌ی تجربیاتم توی حوزه‌ی فرونت اند و برنامه سازی توسط جاوااسکریپته. گاه گداری هم از سنیما، تیاتر، ادبیات و کلا هر چیزی که به هنر و اجتماع مربوط باشه و نباشه.

copyright: "Commons Attribution 4.0 International"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      author: "سید ناصر حسنی"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      author: "سید ناصر حسنی"


# Where things are
source:          ./src
destination:  ./public
#favicon: "img/favicon.png"


# Handling Reading
encoding:       "utf-8"
include:          [".htaccess", "CNAME", "README.md"]
keep_files:     [".git", "assets"]
exclude:         ["assets", "node_modules", "gulpfile.js", "package.json", "bower.json", "webpack.config.js"]


# Conversion
markdown: kramdown


# Serving
port:    8080


# Outputting
# baseurl: /xyz
permalink: /blog/:year/:title/
paginate_path: /blog/page:num
paginate: 5
timezone: Asia/Tehran


# Plugins
gems:
  - jalalidate
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

